### ISSUE TITLE
Use profile based on assume

### ISSUE THREAD

**Issue by salvadoriume** [one2nc/cloudlens#8]
Hello,
I have in ~/.aws/config

[profile qqq]
  region = eu-west-1
  output = json
 
[profile env_prd]
source_profile = qqq
role_arn = ...

But cloudlens doesn't find profile `env_prd` - any way to make it work? Or any suggestions?
aws-cli works.

**Comment by kubblai** [comment]
+1 otherwise i cant use this awesome app

**Comment by chinmay185** [comment]
Thanks for the details, working on fixing this issue. We are revamping how we read and handle AWS config and secrets. The current method is hand crafted, buggy and very specific. Finding out a better way to read and handle AWS config so that it can support multiple use cases (SSO, JSON config, etc)

**Comment by giorgiocerruti** [comment]
I have another use case. We are using `aws-vault` for managing AWS profiles that set up variables instead of using `auth` and `credentials` files. As a workaround, I've. changed the `GetSession()` function to use `session.NewSession()` in case variables are setup, and other functions according to this. But glad to see another better solution is on its way! Thank you for the amazing tool!  🙏🏻

**Comment by chinmaysomani07** [comment]
Configuration via SSO has been done, and will be enabled in our next release.

**Comment by chinmaysomani07** [comment]
Support for SSO has been enabled in our latest release `v0.1.2`
